version: 2

sources:
  - name: raw_data
    description: Raw seed data from CSV files
    tables:
      - name: blog_posts
        description: Raw blog post data
        columns:
          - name: id
            description: Unique blog post identifier
          - name: title
            description: Blog post title
          - name: slug
            description: URL-friendly identifier
          - name: author_id
            description: Foreign key to authors
          - name: content
            description: Blog post content
          - name: is_published
            description: Publication status
          - name: view_count
            description: Number of views

      - name: authors
        description: Raw author data
        columns:
          - name: id
            description: Unique author identifier
          - name: name
            description: Author name
          - name: email
            description: Author email
          - name: bio
            description: Author biography

